config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  resources :posts
  resources :usuarios, as: :users, only: [:show,:update,:edit] do
    collection do
      get 'reports', to: 'usuarios/reports'
      post 'reports', to: 'usuarios/reports'
      get 'explore', to: 'usuarios/explore'
      post 'explore', to: 'usuarios/explore'
      get 'conversations'
    end
  end
  resources :friendships, only: [:create,:update,:destroy]
  resources :likes, only: [:create,:update,:destroy]
  resources :chat_rooms, only: [:new,:create,:show,:index]
  resources :donations do
    collection do
      get 'mercadopago'
    end
  end
  resources :comments
  resources :organization_certificates do
    collection do
      get 'registration'
    end
  end

  devise_for :users, controllers:{
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "users/registrations"
  }

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  post "/donations/:id" => "donations#show"
  post "/hook" => "donations#hook"

  get 'main/join'
  get 'main/learn'

  authenticated :user do
    root 'main#home'
  end
  unauthenticated :user do
    root 'main#unregistered'
  end

  resource :organization_registration do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  belongs_to :friend,class_name: "User"
  has_many :messages, dependent: :destroy
  validates :user_id, uniqueness:{scope: :friend_id,message:"Conversacion Duplicada"}

  def get_friend(user,chat_room)
    if chat_room.user == user
      return chat_room.friend
    else
      return chat_room.user
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_owner!, only: [:show]

  def index
    @chat_rooms = ChatRoom.where(user:current_user)
                          .or(ChatRoom.where(friend:current_user))
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    @chat_room.friend = User.find(params[:chat_room][:friend])
    respond_to do |format|
      if @chat_room.save
        format.html{redirect_to @chat_room}
      else
        format.html{redirect_to chat_rooms_path}
      end
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end

  def authenticate_owner!
    @chat_room = ChatRoom.find(params[:id])
    if (current_user != @chat_room.user) && (current_user != @chat_room.friend)
      redirect_to root_path, notice: "No estas autorizado", status: :unauthorized
    end
  end
end

app/views/chat_rooms/_chat_room.haml
- friend = chat_room.get_friend(current_user,chat_room)
.x_panel
  .row.middle-xs
    .col-md-2.col-xs-2
      %img.img-circle.img-responsive{ :src => friend.avatar.url(:thumb)}
    .col-md-10.col-xs-10
      .row
        %h2
          %li.remove-bullet-points= link_to "#{friend.name+friend.last_name++" @"+friend.username}", chat_room_path(chat_room)

app/views/chat_rooms/_form.haml
- id = "chat_room_form" if local_assigns[:id].nil?
=form_for @chat_room,:html => {:id => id, :remote => true, 'data-type' => 'html'} do |f|
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control'
  .form-group
    = f.label :friend
    = f.select :friend, options_for_select(Friendship.user_following(current_user).map{|s|[s.friend.name, s.friend.id]}),{},{class: 'form-control'}
  = f.submit "Add!", class: 'btn btn-primary'

app/views/chat_rooms/_new.haml
.modal-dialog
  .row
    .modal-dialog
      .box.box-primary
        / Modal content
        .modal-content
          .modal-header
            .box-header.with-border
              %button.close.modal-close-icon{"data-dismiss" => "modal", :type => "button"}
              %h4.modal-title{:style => "text-align: center;"} Crear Conversación
          .modal-body
            .box-body
              = render 'form'
          .modal-footer
            %button.btn.btn-default.modal-close{"data-dismiss" => "modal", :type => "button"} Close

app/views/chat_rooms/index.haml
.right_col{:role => "main"}
  %div
    .clearfix
    .row.little-padding
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_title
            %h2#content-user-name
              Conversaciones
              %small
                Historial
            .clearfix
          .x_content
            %p.lead= link_to '<i class="fa fa-plus"></i> Nueva Conversación'.html_safe, new_chat_room_path,remote:true, class: 'btn btn-primary', 'data-type' => 'script'
            %ul
              = render @chat_rooms
      #ModalNew.modal.fade

app/views/chat_rooms/new.js.erb
$("#ModalNew").html("<%= escape_javascript(render 'new') %>")
$("#ModalNew").modal("show")

app/views/chat_rooms/show.haml
- friend = @chat_room.get_friend(current_user,@chat_room)
.right_col{:role => "main"}
  %div
    .clearfix
    .row.little-padding
      .col-md-10.col-sm-10.col-xs-10.col-xs-offset-1.col-md-offset-1.col-sm-offset-1
        .x_panel
          .x_title
            .row.middle-xs
              .col-md-10.col-sm-10.col-xs-8
                %h1= " @"+friend.username
              .col-md.col-sm.col-xs.center-xs
                =link_to '<h4><i class="fa fa-mail-reply"></i> Conversaciones</h4>'.html_safe,chat_rooms_path
          .x_content
            #messages.chat_panel{"data-chat-room-id" => "#{@chat_room.id}"}
              = render @chat_room.messages
            = form_for @message, url: '#' do |f|
              .form-group.little-padding
                = f.label "Mensaje"
                = f.text_area :body, class: 'form-control'
                %small.text-muted From 2 to 1000 characters
              = f.submit "Enviar", class: 'btn btn-primary btn-lg'