config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  resources :posts
  resources :usuarios, as: :users, only: [:show,:update,:edit] do
    collection do
      get 'reports', to: 'usuarios/reports'
      post 'reports', to: 'usuarios/reports'
      get 'explore', to: 'usuarios/explore'
      post 'explore', to: 'usuarios/explore'
      get 'conversations'
    end
  end
  resources :friendships, only: [:create,:update,:destroy]
  resources :likes, only: [:create,:update,:destroy]
  resources :chat_rooms, only: [:new,:create,:show,:index]
  resources :donations do
    collection do
      get 'mercadopago'
    end
  end
  resources :comments
  resources :organization_certificates do
    collection do
      get 'registration'
    end
  end

  devise_for :users, controllers:{
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "users/registrations"
  }

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  post "/donations/:id" => "donations#show"
  post "/hook" => "donations#hook"

  get 'main/join'
  get 'main/learn'

  authenticated :user do
    root 'main#home'
  end
  unauthenticated :user do
    root 'main#unregistered'
  end

  resource :organization_registration do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end

end

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer class="footer">
  <div class="pull-right" style="clear: both;">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentellela Alela!</span></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "img.jpg", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welcome,</span>
          <h2>John Doe</h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
          <h3>General</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="index.html">Dashboard</a>
                </li>
                <li><a href="index2.html">Dashboard2</a>
                </li>
                <li><a href="index3.html">Dashboard3</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="form.html">General Form</a>
                </li>
                <li><a href="form_advanced.html">Advanced Components</a>
                </li>
                <li><a href="form_validation.html">Form Validation</a>
                </li>
                <li><a href="form_wizards.html">Form Wizard</a>
                </li>
                <li><a href="form_upload.html">Form Upload</a>
                </li>
                <li><a href="form_buttons.html">Form Buttons</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="general_elements.html">General Elements</a>
                </li>
                <li><a href="media_gallery.html">Media Gallery</a>
                </li>
                <li><a href="typography.html">Typography</a>
                </li>
                <li><a href="icons.html">Icons</a>
                </li>
                <li><a href="glyphicons.html">Glyphicons</a>
                </li>
                <li><a href="widgets.html">Widgets</a>
                </li>
                <li><a href="invoice.html">Invoice</a>
                </li>
                <li><a href="inbox.html">Inbox</a>
                </li>
                <li><a href="calendar.html">Calendar</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="tables.html">Tables</a>
                </li>
                <li><a href="tables_dynamic.html">Table Dynamic</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="chartjs.html">Chart JS</a>
                </li>
                <li><a href="chartjs2.html">Chart JS2</a>
                </li>
                <li><a href="morisjs.html">Moris JS</a>
                </li>
                <li><a href="echarts.html">ECharts </a>
                </li>
                <li><a href="other_charts.html">Other Charts </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="menu_section">
          <h3>Live On</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="e_commerce.html">E-commerce</a>
                </li>
                <li><a href="projects.html">Projects</a>
                </li>
                <li><a href="project_detail.html">Project Detail</a>
                </li>
                <li><a href="contacts.html">Contacts</a>
                </li>
                <li><a href="profile.html">Profile</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="page_404.html">404 Error</a>
                </li>
                <li><a href="page_500.html">500 Error</a>
                </li>
                <li><a href="plain_page.html">Plain Page</a>
                </li>
                <li><a href="login.html">Login Page</a>
                </li>
                <li><a href="pricing_tables.html">Pricing Tables</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="#level1_1">Level One</a>
                <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li class="sub_menu"><a href="level2.html">Level Two</a>
                    </li>
                    <li><a href="#level2_1">Level Two</a>
                    </li>
                    <li><a href="#level2_2">Level Two</a>
                    </li>
                  </ul>
                </li>
                <li><a href="#level1_2">Level One</a>
                </li>
              </ul>
            </li>
            <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a>
            </li>
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<div class="row">
  <div class="col-md-12 col-xs-12">
    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <butto type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </butto>
              <a><h1 class="blue" style="font-size: 25px;"> BeneCom</h1></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "HOME",root_path,class:"text-letter-spacing grey-title"%></li>
                <li><%= link_to "JOIN",{ controller: "/main", action: "join"},class:"text-letter-spacing grey-title"%></li>
                <li><%= link_to "LEARN",{ controller: "/main", action: "learn"},class:"text-letter-spacing grey-title"%></li>

              </ul>
              <% if user_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a id="topnav-user-name" href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <%= image_tag current_user.avatar.url(:thumb), id:"navbar-user-image" %>
                    <%=if current_user.name && current_user.last_name
                         current_user.name+" "+current_user.last_name
                        end %>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li>
                      <%= link_to "Perfil",user_path(current_user.id)%>
                    </li>
                    <li>
                      <%= link_to "Donaciones",donations_path%>
                    </li>
                    <%if current_user.is_organization? %>
                        <li>
                          <%= link_to "Reportes",reports_users_path%>
                        </li>
                    <% end %>
                    <li>
                      <%= link_to "Ayuda",{ controller: "/main", action: "learn"}%>
                    </li>
                    <li>
                      <%= link_to "<i class='fa fa-sign-out pull-right'></i>Cerrar Sesion".html_safe,destroy_user_session_path, method: :delete%>

                    </li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <div class="text-center">
                        <%=link_to '<strong>Ver Conversaciones</strong> <i class="fa fa-angle-right"></i>'.html_safe,chat_rooms_path %>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
              <% end %>
            </div><!--/.nav-collapse -->
          </div><!--/.container-fluid -->
        </nav>

      </div>
    </div>
    <!-- /top navigation -->
  </div>
</div>

app/views/partials/_user_navbar.haml
%ul.remove-bullet-points
  .left-list-padding.profile.clearfix
    .profile_pic
      = image_tag current_user.avatar.url(:thumb),class:"img-circle profile_img"
    .profile_info
      - if current_user.name && current_user.last_name
        %p=current_user.name+" "+current_user.last_name
  %li.left-list-padding=link_to "<span class='glyphicon glyphicon-search'> Explorar</span>".html_safe,explore_users_path
  %li.left-list-padding=link_to "<span class='glyphicon glyphicon-flag'> Sugerencias</span>".html_safe,{ controller: "/main", action: "join"}
  %li.left-list-padding=link_to "<span class='glyphicon glyphicon-home'> Benecom</span>".html_safe,{ controller: "/main", action: "home"}
  %li.left-list-padding=link_to "<span class='glyphicon glyphicon-user'> Contacto</span>".html_safe,{ controller: "/main", action: "learn"}