config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  resources :posts
  resources :usuarios, as: :users, only: [:show,:update,:edit] do
    collection do
      get 'reports', to: 'usuarios/reports'
      post 'reports', to: 'usuarios/reports'
      get 'explore', to: 'usuarios/explore'
      post 'explore', to: 'usuarios/explore'
      get 'conversations'
    end
  end
  resources :friendships, only: [:create,:update,:destroy]
  resources :likes, only: [:create,:update,:destroy]
  resources :chat_rooms, only: [:new,:create,:show,:index]
  resources :donations do
    collection do
      get 'mercadopago'
    end
  end
  resources :comments
  resources :organization_certificates do
    collection do
      get 'registration'
    end
  end

  devise_for :users, controllers:{
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "users/registrations"
  }

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  post "/donations/:id" => "donations#show"
  post "/hook" => "donations#hook"

  get 'main/join'
  get 'main/learn'

  authenticated :user do
    root 'main#home'
  end
  unauthenticated :user do
    root 'main#unregistered'
  end

  resource :organization_registration do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end

end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Friendship < ApplicationRecord
  include AASM
  belongs_to :user
  belongs_to :friend,class_name: "User"
  validates :user_id, uniqueness:{scope: :friend_id,message:"Amistad Duplicada"}

  def self.friends?(user,friend)
    Friendship.where(user:user,friend:friend)
              .or(Friendship.where(user:friend,friend:user))
              .any?
  end

  def self.following?(user,friend)
    Friendship.where(user:user,friend:friend).any?
  end

  def self.user_following(user)
    Friendship.active.where(user: user)
  end

  def self.user_followers(user)
    Friendship.active.where(friend: user)
  end

  aasm column: "status" do
    state :pending
    state :active, initial: true
    state :denied

    event :accepted do
      transitions from: [:pending], to: [:active]
    end
    event :rejected do
      transitions from: [:pending,:active], to: [:denied]
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :find_friend

  def create
    @friendship = Friendship.new(user: current_user, friend: @friend)
    respond_to do |format|
      if @friendship.save
        @are_friends = current_user.my_friend?(@friend)
        format.html{redirect_to @friend}
        format.js{}
      else
        format.html{redirect_to @friend,notice:"Error con la solicitud de amistad"}
        format.js{redirect_to @friend,notice:"Error con la solicitud de amistad"}
      end
    end
  end

  def destroy
    @friendship = Friendship.where(user: current_user, friend: @friend).first()
    if @friendship.present?
      respond_to do |format|
        if @friendship.destroy
          format.html { redirect_to @friend }
          format.js {}
        else
          format.html { redirect_to @friend, notice:"Error con la solicitud de amistad" }
          format.js { redirect_to @friend, notice:"Error con la solicitud de amistad" }
        end

      end
    end
  end

  private
  def find_friend
    @friend = User.find(params[:friend_id])
  end

  def find_model
    @model = Friendship.find(params[:id]) if params[:id]
  end
end

app/views/friendships/_follow_buttons.haml
- if @are_friends
  = link_to '<i class="fa fa-check"></i> Siguiendo'.html_safe,{ action: :destroy, id: @friendship.id, friend_id: @friend.id },method: :delete, remote: true, class: "btn btn-primary btn-follow", 'data-type' => 'script',clicked: false
- else
  = link_to '<i class="fa fa-plus"></i> Seguir'.html_safe,friendships_path(friend_id: @friend.id),method: :post, remote: true, class: "btn btn-info btn-follow", 'data-type' => 'script',clicked: false

app/views/friendships/_friendship.haml
.x_panel
  .row.middle-xs
    .col-md-2.col-xs-2
      %img.img-circle.img-responsive{ :src => friendship.friend.avatar.url(:thumb)}
    .col-md-8.col-xs-8
      %h2=link_to friendship.friend.username,friendship.friend
    - if current_user != friendship.friend
      .col-md-2.col-xs-2
        - if current_user.is_following?(friendship.friend)
          = link_to '<i class="fa fa-check"></i> Siguiendo'.html_safe,friendship_path(friend_id: friendship.friend.id),method: :delete, remote: true, class: "btn btn-primary btn-follow", 'data-type' => 'script',clicked: false
        - else
          = link_to '<i class="fa fa-plus"></i> Seguir'.html_safe,friendships_path(friend_id: friendship.friend.id),method: :post, remote: true, class: "btn btn-info btn-follow", 'data-type' => 'script',clicked: false

app/views/friendships/_user_followers.haml
.x_panel
  .row.middle-xs
    .col-md-2.col-xs-2
      %img.img-circle.img-responsive{ :src => user_followers.user.avatar.url(:thumb)}
    .col-md-8.col-xs-8.middle-xs
      %h2=user_followers.user.username
    - if current_user != user_followers.user
      .col-md-2.col-xs-2
        - if current_user.is_following?(user_followers.user)
          = link_to '<i class="fa fa-check"></i> Siguiendo'.html_safe,friendship_path(friend_id: user_followers.user.id),method: :delete, remote: true, class: "btn btn-primary btn-follow", 'data-type' => 'script',clicked: false
        - else
          = link_to '<i class="fa fa-plus"></i> Seguir'.html_safe,friendships_path(friend_id: user_followers.user.id),method: :post, remote: true, class: "btn btn-info btn-follow", 'data-type' => 'script',clicked: false

app/views/friendships/create.js.erb
$("a.btn-follow[clicked='true']").replaceWith("<%= j render 'friendships/follow_buttons' %>");

app/views/friendships/destroy.js.erb
$("a.btn-follow[clicked='true']").replaceWith("<%= j render 'friendships/follow_buttons' %>");