config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  resources :posts
  resources :usuarios, as: :users, only: [:show,:update,:edit] do
    collection do
      get 'reports', to: 'usuarios/reports'
      post 'reports', to: 'usuarios/reports'
      get 'explore', to: 'usuarios/explore'
      post 'explore', to: 'usuarios/explore'
      get 'conversations'
    end
  end
  resources :friendships, only: [:create,:update,:destroy]
  resources :likes, only: [:create,:update,:destroy]
  resources :chat_rooms, only: [:new,:create,:show,:index]
  resources :donations do
    collection do
      get 'mercadopago'
    end
  end
  resources :comments
  resources :organization_certificates do
    collection do
      get 'registration'
    end
  end

  devise_for :users, controllers:{
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "users/registrations"
  }

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  post "/donations/:id" => "donations#show"
  post "/hook" => "donations#hook"

  get 'main/join'
  get 'main/learn'

  authenticated :user do
    root 'main#home'
  end
  unauthenticated :user do
    root 'main#unregistered'
  end

  resource :organization_registration do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  scope :nuevos, ->{order("created_at desc")}

  def self.all_for_user(user)
    Post.where(user_id: user.id)
        .or( Post.where(user_id: user.friend_ids))
  end
  def self.user_likes?(current_user)

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    session[:post_id] = @post.id
    @comment = Comment.new
    @comments = Comment.where(post:@post).nuevos.paginate(page:params[:page],per_page:5)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { render :partial => 'post' }
        format.json { render json: @post.to_json}
      else
        format.html{ render json: (@post.errors).to_json, status: :unprocessable_entity }
        format.json{ render json: (@post.errors).to_json, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.haml
- id = "post-form" if local_assigns[:id].nil?
=form_for @post,:html => {:id => id, :remote => true, 'data-type' => 'html'} do |f|
  .form-group
    = f.label :body,"Comprate con la comunidad", class:"text-left"
    = f.text_area :body, autofocus: true, class:"form-control"
  .actions
    = f.submit 'Publicar', class:"btn btn-primary"

app/views/posts/_post.haml
- post = @post if local_assigns[:post].nil?
.x_panel
  .row
    .col-md-2.col-xs-2
      %img.img-circle.img-responsive{ :src => post.user.avatar.url(:thumb)}
    .col-md-10.col-xs-10
      .row
        %h4= link_to post.user.name+post.user.last_name+" @"+post.user.username,post.user
      .row.post_body
        =post.body
      .row.post_footer
        %p.post-blue=(post.likes_count).to_s
        -like = Like.where(user:current_user,post:post)
        - unless current_user.likes?(post)
          = link_to '<i class="fa fa-thumbs-o-up"></i> Me Gusta'.html_safe,likes_path(post_id: post.id),method: :post, remote: true,style: "padding-left:5px;", class: "btn-like", 'data-type' => 'script',clicked: false
        - else
          = link_to '<i class="fa fa-thumbs-up"></i> Me Gusta'.html_safe,like_path(like,post_id: post.id),method: :delete, remote: true, style: "padding-left:5px;",class: "btn-like", 'data-type' => 'script',clicked: false
        %p.post-blue{style:"padding-left:15px;"}=(post.comments_count).to_s
        =link_to '<i class="fa fa-comment-o"></i> Comentar'.html_safe,post,{style:"padding-left:5px;"}

app/views/posts/create.js.erb
$("#posts").prepend("<%= j render @post%>")

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Body
      %th User
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.body
        %td= post.user
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/like.js.erb
$('.like_clicked').html("<i class='fa fa-thumbs-up'></i> Me Gusta");
$('.like_clicked').removeClass("like_clicked");

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.haml
- post = @post if local_assigns[:post].nil?
.right_col{role:"main"}
  .row.big-padding
    .col-md-12.col-sm-12.col-xs-12
      .row
        .col-md-3.col-sm-3.col-xs-12{id:"left-home-list"}
          = render 'partials/user_navbar'
        .col-md-6.col-sm-6.col-xs-12
          .x_panel
            .row
              .col-md-2.col-xs-2
                %img.img-circle.img-responsive{ :src => post.user.avatar.url(:thumb)}
              .col-md-10.col-xs-10
                .row
                  %h4=post.user.name+post.user.last_name+" @"+post.user.username
                .row.post_body
                  =post.body
                .row.post_footer
                  =link_to '<i class="fa fa-thumbs-o-up"></i> Me Gusta'.html_safe,root_path
          .x_panel
            =render 'comments/form'
          #comments
            .data
              =render @comments
            #pagination
              =will_paginate @comments